[package]
name = "agentx-acp-ui"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
agent-client-protocol = { workspace = true, features = ["unstable"] }
gpui.workspace = true
gpui-component.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
similar.workspace = true

[dev-dependencies]
anyhow.workspace = true
gpui-component-assets = { git = "https://github.com/sxhxliang/gpui-component", branch = "dev" }

[lints.rust]
dead_code = "allow"
unused_variables = "allow"
unused_imports = "allow"

[lints.clippy]
style = { level = "allow", priority = -1 }
module_inception = "allow"
